### ISSUE TITLE
react-lenis with GSAP ScrollTrigger

### ISSUE THREAD

**Issue by ymhaah** [studio-freight/react-lenis#14]
Is there anything specific I need to do in order to use it with GSAP ScrollTrigger?

**Comment by kaneel** [comment]
I'm currently wondering the same because in the normal lenis documentation there's a mention of integrating with Scrolltrigger while in this package, lenis seems rather opinionated by hooking the `raf` method for us; If I follow the tip for hooking up the gsap ticker with lenis raf, it starts glitching. 

Should we setup lenis manually when using GSAP + Scrolltrigger?

**Comment by clementroche** [comment]
hey nice catch @kaneel, react-lenis uses its own internal raf based on [@studio-freight/tempus](https://www.npmjs.com/package/@studio-freight/tempus). I'm gonna let the users the ability to use the raf they want in the next version

**Comment by clementroche** [comment]
It's now available in v0.0.22. See GSAP integration in the [readme](https://github.com/studio-freight/react-lenis/blob/main/README.md#examples)

**Comment by liho00** [comment]
hi guys, I am still confusing whats the different and usage of Lenis vs [Gsap ScrollTrigger](https://greensock.com/scrolltrigger/) vs [Gsap SmoothScroll](https://greensock.com/scrollsmoother/)

Could anyone provide simple example or explanation of these package differences?

**Comment by clementroche** [comment]
First of all you can only compare Lenis to ScrollSmoother but not to ScrollTrigger. ScrollTrigger provides an scroll-driven animation system, while Lenis and ScrollSmoother both provide smooth scrolling solution.

Now here is the the main differences between Lenis and ScrollSmoother :
- Lenis is based on scrollTo API while ScrollSmoother is based on CSS transform, so Lenis should be more performant in 99% of cases and does not erase browser default accessibility.
- Lenis is free and open source while ScrollSmoother is a paid package.
- Lenis is 4kb while ScrollSmooter is 12kb.
- some specific options (see both documentations)

**Comment by liho00** [comment]
> First of all you can only compare Lenis to ScrollSmoother but not to ScrollTrigger. ScrollTrigger provides an scroll-driven animation system, while Lenis and ScrollSmoother both provide smooth scrolling solution.
> 
> Now here is the the main differences between Lenis and ScrollSmoother :
> 
> * Lenis is based on scrollTo API while ScrollSmoother is based on CSS transform, so Lenis should be more performant in 99% of cases and does not erase browser default accessibility.
> * Lenis is free and open source while ScrollSmoother is a paid package.
> * Lenis is 4kb while ScrollSmooter is 12kb.
> * some specific options (see both documentations)

I see, great lenis, thanks for the explanation, appreaciated.
Will proceed and start learning with Lenis.
Have a nice day man!
