### ISSUE TITLE
How to use lenis.stop() in useEffect?

### ISSUE THREAD

**Issue by chanayus** [studio-freight/react-lenis#16]
```javascript
 const lenis = useLenis();

  useEffect(() => {
    if (lenis) {
     lenis.stop()
    }
  }, [lenis]);
```

Hello! I have tried to use lenis.stop() in useEffect, but it's not working.
My project is Next.js 13.4 (Typescript)

**Comment by arzafran** [comment]
@chanayus  what was the issue? maybe someone else can also benefit from your solution

**Comment by chanayus** [comment]
@arzafran 
The issue was I have setup Lenis in the main layout component, and I want to disable scroll until the animation of the header component is finished by using lenis.stop() in the useEffect of the header component, but it's not working. So I choose to use lenis.stop() from the main layout component and lenis.start() in header components when animation is finished.
