### ISSUE TITLE
Issue with server-side log in Next 13

### ISSUE THREAD

**Issue by kilimanjjjaro** [studio-freight/react-lenis#17]
Hello, I'm getting the following log on the server when using the library in Next 13. I think it's because of the dependency @studio-freight/tempus, which is used by Lenis
```
Tempus can be used in client side only
```
I suppose the log is because the client components are first rendered on the server and then rehydrated on the client, but it's a bit annoying. Is there any way to hide or cover this corner case? I assume the library's compatibility with Next 13 is still in development.

This is the client component:
```jsx
'use client'

import { ReactLenis } from '@studio-freight/react-lenis'
import type { ChildrenInterface } from '@/interfaces/general'

export default function SmoothScroll({ children }: ChildrenInterface) {
  return (
    <ReactLenis root options={{ duration: 1.2 }}>
      {children}
    </ReactLenis>
  )
}
```

This is the server component where it is used:
```jsx
import SmoothScroll from '@/components/shared/SmoothScroll'
import type { ChildrenInterface } from '@/interfaces/general'
import '@/app/globals.css'

export default function RootLayout({ children }: ChildrenInterface) {
  return (
    <html lang='en'>
      <body className='antialiased'>
        <SmoothScroll>{children}</SmoothScroll>
      </body>
    </html>
  )
}
```

### Package versions
- Next: 13.4.7
- @studio-freight/react-lenis: 0.0.21

I hope you're ok, guys!

**Comment by clementroche** [comment]
You must use latest Tempus version 

https://www.npmjs.com/package/@studio-freight/tempus
