### ISSUE TITLE
Could not find a declaration file for module '@studio-freight/react-lenis'

### ISSUE THREAD

**Issue by piscopancer** [studio-freight/react-lenis#19]
![image](https://github.com/studio-freight/react-lenis/assets/109352196/9370b49b-d4c2-469e-a7f5-04fc5c4010aa)

**Comment by Splact** [comment]
Just bumped on the same issue too

**Comment by clementroche** [comment]
it should be fixed with version 0.0.24

**Comment by clementroche** [comment]
@piscopancer is it fixed ?

**Comment by piscopancer** [comment]
You pushed an update ok got it, when I am back home I am gonna check it out ⚡

**Comment by piscopancer** [comment]
@clementroche it is not typed at all whadteee... 
```ts
/**
 * @param {boolean=} [root] Whether Lenis will be initialized on document.documentElement
 * @param {Object=} [options={}] Lenis options
 * @param {boolean=} [autoRaf=true] Whether to call Lenis.raf automatically on every frame
 * @param {number=} [rafPriority=0] Priority of Lenis.raf call (lower priority callbacks are called first)
 */
export const ReactLenis: any; // 😭
```
can you get types from normal lenis and push them to this react version? that would be ease, must be easy, idk. 😎

currently I am using this component (messy af) but it is properly typed hell yeah 🔥
```ts
'use client'

import Lenis from '@studio-freight/lenis'
import { useEffect } from 'react'

export default function LenisScroll() {
	useEffect(() => {
		const lenis = new Lenis({
			duration: 2.5,
		})

		function raf(time: number) {
			lenis.raf(time)
			requestAnimationFrame(raf)
		}

		requestAnimationFrame(raf)
	})

	return <script about='lenis' />
}
```

**Comment by clementroche** [comment]
Is it still throwing errors ? 
If not, i did it right, we don't use Typescript and we don't want to. So we just provide the bare minimum to make it work with TS. However feel free to do a PR if you find a solution for properly  providing the types.

Can I close this issue if your initial error was fixed ?

**Comment by piscopancer** [comment]
> Is it still throwing errors ? If not, i did it right, we don't use Typescript and we don't want to. So we just provide the bare minimum to make it work with TS. However feel free to do a PR if you find a solution for properly providing the types.
> 
> Can I close this issue if your initial error was fixed ?

come on, why are you not using ts. that's 2023. anyway, yes close this issue
