### ISSUE TITLE
Jest issue

### ISSUE THREAD

**Issue by leelongmore** [studio-freight/react-lenis#2]
Hi,

The library is working well in the browser but I see the following error when trying to run my tests:

```
    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /Users/turkeyred/Projects/boxt/boxt-mono/customer-next/node_modules/nanoevents/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){export let createNanoEvents = () => ({
                                                                                      ^^^^^^

    SyntaxError: Unexpected token 'export'

       5 | import { IFlag } from "@flagship.io/js-sdk";
       6 | import { useFsFlag } from "@flagship.io/react-sdk";
    >  7 | import { ReactLenis } from "@studio-freight/react-lenis";
```

I'm using react-lenis 0.0.12 in NextJS 13.0.5 with Jest 29.3.1 and babel-jest 29.3.1

Any pointers appreciated.

Thanks,
Lee.

**Comment by clementroche** [comment]
can you try again with v0.0.13 ?

**Comment by leelongmore** [comment]
Hi Clement,

Thanks for jumping on this and sorry for not replying sooner!

I can confirm that the new release fixes the problem with Jest 🙂

I’ve tried using the library to add smooth scrolling to a page along with a
new parallax effect (using react-spring). Works perfectly on Safari and
Firefox, but the scroll behaviour on Chrome and Edge isn’t working as well.
The scroll appears to pause on both browsers as the element with the
parallax effect comes into view.

When I remove React Lenis, the problem goes away.

Any thoughts on what might be causing this behaviour on Chrome and Edge? A
colleague is also experiencing the same.

I have added “will-change: transform” to each element with the parallax
effect which helped improve performance across all browsers.

Cheers,
Lee.

**Comment by clementroche** [comment]
hey @leelongmore can you provide a codesandbox reproduction link so i can test it by myself ?

**Comment by leelongmore** [comment]
Hey @clementroche, thanks for getting back to me. It's a new page on a large NextJS app that I'm working on for a client. The page hasn't yet been released so I might not be able to provide access to a sandbox but I will ask. In the meantime, is there anything else that I might want to look out for?
