### ISSUE TITLE
Cannot use the useLenis() hook with no parameters

### ISSUE THREAD

**Issue by balraj-johal** [studio-freight/react-lenis#21]
I'd expect to be able to use the useLenis hook with no parameters, for example as seen in the following code snippet:

```
const lenis = useLenis();
const href = `${id}`;

return (
    <NavLinkElement href={href} onClick={() => lenis.scrollTo(href)}>
```

I've dug around in your old commits and made a PR that I think resolves this, but the fallback value may have been removed for a reason I'm not aware of

https://github.com/studio-freight/react-lenis/pull/20

**Comment by clementroche** [comment]
i can't reproduce on my side, can you provide a codesandbox ?

**Comment by balraj-johal** [comment]
@clementroche, I believe it may be a typescript only error, but I have reproduced in this codesandbox:
https://codesandbox.io/s/affectionate-butterfly-8fgz7k?file=/src/App.tsx

This is using the latest version 0.25.0

**Comment by clementroche** [comment]
@balraj-johal there is no `<ReactLenis>` component in your app, so useLenis is useless and returns nothing, but yes callback type is wrong

**Comment by clementroche** [comment]
should be fixed in 0.0.26 @balraj-johal

**Comment by clementroche** [comment]
any news @balraj-johal ? is it fixed ?

**Comment by balraj-johal** [comment]
@clementroche sorry for the delay in responding, but this is fixed on my end with the new version. Thanks for your help!

Would you be open to more comprehensive typing in future? if so I would love to help contribute, as I am personally and professionally using react-lenis in a typescript environment, and would find more type coverage useful

**Comment by clementroche** [comment]
Of course, feel free to PR.

**Comment by balraj-johal** [comment]
@clementroche I've created a PR in which I've added more JSDoc typings, #23
