### ISSUE TITLE
How to "auto-scroll" a lenis instance with infinite:true?

### ISSUE THREAD

**Issue by ndimatteo** [studio-freight/react-lenis#24]
Hey there,

Absolutely loving this library! 🤘 

I'm hoping you can help me understand how I could setup an auto-scrolling animation for a lenis instance that has `infinite: true` set.

To elaborate, I'd like to treat it like a vertical marquee (like a movie credits animation) that scrolls on loop at a steady pace, while still maintaining the mouse/wheel scroll capabilities.

I've tried setting up a `gsap.to()` animation with the `ScrollToPlugin` like this in my component:

```js
const creditsRef = useRef(null)
const lenis = useLenis()

useEffect(() => {
  function update(time) {
    creditsRef.current?.raf(time * 1000)
  }

  gsap.ticker.add(update)

  return () => {
    gsap.ticker.remove(update)
  }
})

useEffect(() => {
  if (!lenis) return

  if (creditsRef.current) {
    gsap.to(creditsRef.current.rootElement, {
      duration: 1,
      scrollTo: {
        y: () => creditsRef.current.rootElement.scrollTop + 100,
      },
      duration: 1,
      repeat: -1,
      overwrite: true,
      ease: 'linear',
      repeatRefresh: false,
    })
  }
}, [lenis, creditsRef])

return (
  <Lenis
    ref={creditsRef}
    autoRaf={false}
    options={{
      infinite: true,
    }}
  >
    {/* lenis content... */}
  </Lenis>
)
```

This works in that it scrolls the lenis container, but I can't seem to get it to properly set the `y` position as it seems to use the same distance `0 -> 100` on repeat.

I'm not sure if this is (1) the proper way to animate the lenis scroll position continuously, or (2) how to properly pass the lenis scroll position to the `scrollTo` value when it repeats.

Would love to hear your ideas on how to achieve something like this! Thanks so much

**Comment by clementroche** [comment]
can you reproduce it on codesandbox ? So it's easier to test and debug

**Comment by ndimatteo** [comment]
Hey @clementroche absolutely! Sorry I didn't include that initially 😅 

Here's a codesandbox with what I described: https://codesandbox.io/p/sandbox/lenis-auto-scroll-56lmk5

Let me know what you think!

**Comment by clementroche** [comment]
here is how i would do it https://codesandbox.io/p/sandbox/lenis-auto-scroll-forked-2y9vv9?file=%2Fcomponents%2Fcredits.js%3A47%2C37

```js
function onFrame(time,deltaTime) {
   lenis.scrollTo(lenis.scroll + deltaTime * 0.1, { immediate: true })
 }

gsap.ticker.add(onFrame)
```

**Comment by ndimatteo** [comment]
@clementroche I like this! Only major issue seems to be that when manually trying to scroll it seems incredibly sluggish compared to the default without this running?

I'm wondering if the `onFrame` being called continuously while also trying to scroll manually is causing a collision that affects the scroll velocity/lerping/etc?

**Comment by clementroche** [comment]
would you like to be able to scroll at the same time ?

**Comment by ndimatteo** [comment]
Yea I think the idea would be that you could "take over" the scrolling at any time and scroll like you normally would with Lenis, and then if you stop scrolling the `onFrame` resumes.

**Comment by clementroche** [comment]
it complexifies a lot the script but it works

https://codesandbox.io/p/sandbox/lenis-auto-scroll-forked-2y9vv9?file=%2Fcomponents%2Fcredits.js%3A53%2C6

**Comment by ndimatteo** [comment]
Actually @clementroche I might have found a simpler solution?

Since you're setting the scroll position with `immediate` it doesn't cause the `isScrolling` value to change, that only triggers on manual scroll, so you can just bail out in the function when that happens:

```js
useEffect(() => {
  function onFrame(time, deltaTime) {
    const lenis = creditsRef?.current

    if (lenis?.isScrolling) return

    lenis?.scrollTo(lenis.scroll + deltaTime * 0.1, { immediate: true })
  }

  gsap.ticker.add(onFrame)

  return () => {
    gsap.ticker.remove(onFrame)
  }
})
```

Updated the codesandbox here: https://codesandbox.io/p/sandbox/lenis-auto-scroll-56lmk5

**Comment by clementroche** [comment]
perfect

**Comment by ndimatteo** [comment]
awesome, appreciate the quick set of eyes on this one! 🤘
