### ISSUE TITLE
Calling lenis.stop() on root instance causes all instances to become unscrollable on touch devices

### ISSUE THREAD

**Issue by ndimatteo** [studio-freight/react-lenis#25]
When using multiple instances of Lenis (notably for dialogs, meganvas, etc.) I need a way to pause the underlying root Lenis instance.

I was able to solve this by doing the following:
```js
const [isOpen, setIsOpen] = useState(false)

const lenis = useLenis()

useEffect(() => {
  if (isOpen && lenis?.rootElement === document.documentElement) {
    lenis?.stop()
  } else if (lenis?.rootElement === document.documentElement) {
    lenis?.start()
  }
}, [isOpen])
```

this works perfectly on desktop, but seems to cause _all_ lenis instances to break on touch devices. I'm unable to scroll my other active instances when `lenis?.stop()` is called.

Is there a better way to handle stopping the root lenis instance when I don't have access to the `ref` from other deeply nested components?

**Comment by clementroche** [comment]
please reproduce it on codesandbox

**Comment by ndimatteo** [comment]
@clementroche updated here: https://codesandbox.io/p/sandbox/lenis-auto-scroll-56lmk5

**Comment by ndimatteo** [comment]
Also can confirm that even if I store my root `lenisRef` in a global state and call the `stop()` method on that specifically the issue persists, where other lenis instances have their scrolling break on touch devices.

This tells me it may be unrelated to how the `useLenis` hook works, and more to do with the stop method itself?

**Comment by clementroche** [comment]
i don't know what i have to look at, too many things are happening, can you simplify this by removing autoscroll etc. I think it's disturbing to solve your issue

**Comment by ndimatteo** [comment]
@clementroche sure thing!

I just removed some of the extra stuff. It's only a root Lenis instance + a nested Lenis instance inside of a dialog (pop-up).

The issue remains that on **touch devices** scrolling fails to work on the nested Lenis instance when calling `stop()` on the root Lenis instance (this is handled [here, within the dialog component](https://codesandbox.io/p/sandbox/lenis-auto-scroll-56lmk5?file=/components/dialog.js:70,1-77,1))

**Comment by ndimatteo** [comment]
Hey there @clementroche just following up here, any chance you were able to review the simplified version showing this issue?

**Comment by clementroche** [comment]
@ndimatteo  you need `data-lenis-prevent` on your modal Lenis wrapper

```js
<Lenis data-lenis-prevent>
```

**Comment by ndimatteo** [comment]
Hey there @clementroche 

I'm not sure I follow. If I add that to the modal Lenis instance it prevents that Lenis instance from functioning properly...

The goal is to have both instances work properly, with the Root instance pausing when scrolling the modal Lenis.

Again, this works on Desktop, but fails on touch devices.

**Comment by clementroche** [comment]
can you add it to the wrapper instead ? I can't fork your codesandbox to fix it for reason

```js
<div data-lenis-prevent>
    <Lenis>
</div>
````

**Comment by ndimatteo** [comment]
Adding `data-lenis-prevent` to any parent element prevents the nested Lenis from running. It just goes back to the native scroll.

You should be able to fork my codesandbox, it's public.

**Comment by clementroche** [comment]
Can you try `data-lenis-prevent-touch` instead of `data-lenis-prevent`.

```js
<Lenis data-lenis-prevent-touch>
```

If you want infinite on touch too you'll need `syncTouch: true` instead

https://codesandbox.io/p/sandbox/lenis-auto-scroll-forked-xfsjll?file=/components/credits.js:70,35

But there is definitly something wrong in the Lenis codebase, I need time to figure out the best way to handle such things

**Comment by clementroche** [comment]
Any news ? 
Lenis v1.0.22 should fix it

**Comment by ndimatteo** [comment]
Hey there @clementroche, I just tested this.

If I add `syncTouch: true` that seems to help the issue with nested Lenis instances! However, adding `data-lenis-prevent-touch` to any element (the Lenis component itself, or any parent components) prevents the nested Lenis from working (notably infinite breaks as well).

Do you know when the update in Lenis v1.0.22 will be implemented here for the `react-lenis` version? Happy to test it out once it is!

Thanks again for taking a look at this 🤘

**Comment by clementroche** [comment]
react-lenis is lenis version agnostic meaning it just gonna use the version of lenis you installed.

btw everything works fine on my [codesandbox](https://codesandbox.io/p/sandbox/lenis-auto-scroll-forked-xfsjll?file=/components/credits.js:70,35)

`infinite` doesn't work without `syncTouch: true`

**Comment by ndimatteo** [comment]
got it @clementroche! This seems to work well now (without the need to use `data-lenis-prevent-*`).

Appreciate your time looking into this, thank you! 🤘
