### ISSUE TITLE
Warning: Maximum update depth exceeded.

### ISSUE THREAD

**Issue by fransjesky** [studio-freight/react-lenis#27]
Hi! I am using react-lenis on my project and everything is actually working fine.
However i notice an error log in console that would appear if i scroll really fast. It would be like this:

<img width="554" alt="Screenshot 2023-09-03 at 05 08 04" src="https://github.com/studio-freight/react-lenis/assets/52071677/a112ca70-e297-4c51-a365-ea886aa95357">

I've installed react-lenis in a nextjs as a hook.

```ts
// hooks/useSmooth

'use client';

import { ReactLenis } from '@studio-freight/react-lenis';

export default function SmoothScroll({
  children,
}: {
  children: React.ReactNode;
}) {
  return <ReactLenis root>{children}</ReactLenis>;
}
```

Then i imported it to the layout.tsx
```ts
// app/layout.tsx

import SmoothScroll from '@/hooks/useSmooth';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>
        <SmoothScroll>
          <Navigation />
          {children}
          <Footer />
        </SmoothScroll>
      </body>
    </html>
  );
}
```

I already tried to disable and remove the react-lenis from my app and the error log never appears anymore until i use it again. I'm not really sure if this error is coming from react-lenis or is it because i implemented it wrong.

**Comment by clementroche** [comment]
please provide a codesandbox

**Comment by fransjesky** [comment]
the way i use reaact-lenis is literally like the one i provided, the rest is codes from my personal project. for the layout it would precisely be like this.

just like i explained before, the SmoothScroll component is a hook of react-lenis that i created so i can put 'use client' due to the requirement from nextjs for csr

```ts
// app/layout.tsx

import { Analytics } from '@vercel/analytics/react';
import ThemeRegistry from '@/theme/ThemeRegistry';
import SmoothScroll from '@/hooks/useSmooth';
import { Providers } from '@/redux/providers';
import Navigation from '@/components/Layout/Navigation';
import Footer from '@/components/Layout/Footer';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>
        <Providers>
          <ThemeRegistry>
            <SmoothScroll>
              <Navigation />
              {children}
              <Footer />
            </SmoothScroll>
            <Analytics />
          </ThemeRegistry>
        </Providers>
      </body>
    </html>
  );
}

```

**Comment by clementroche** [comment]
Sorry but i can't do nothing without a codesandbox, i need a minimal reproduction otherwise it can literally be caused by anything
