### ISSUE TITLE
Link to 'compono' in the README returns 404. Are there any other working examples?

### ISSUE THREAD

**Issue by udovichenko** [studio-freight/react-lenis#3]
I wasn't able to get react-lenis work as expected. Do you have any working examples (codesandbox, codepen etc.)?

By the way, the link to [@studio-freight/compono](https://github.com/studio-freight/compono) in README is broken.

Thank you

**Comment by arzafran** [comment]
thanks for the heads up about compono i'll update it, we have a few [sandboxes](https://codesandbox.io/embed/horizontal-scroll-wh50q7?codemirror=1) and also [satus](https://github.com/studio-freight/satus) is our starter using react-lenis
