### ISSUE TITLE
Support for Typescript/VSCode IntelliSense

### ISSUE THREAD

**Issue by cdslxc** [studio-freight/react-lenis#31]
![CleanShot 2023-10-11 at 02 10 36@2x](https://github.com/studio-freight/react-lenis/assets/8092790/e6ce6ecc-855e-4c1c-a818-0afe1a368274)

The <ReactLenis /> component doesn't seem to pick up types from your JSDoc declarations.

**Comment by clementroche** [comment]
I have no idea how to do that, feel free to PR.

**Comment by feledori** [comment]
Feel free to open a pr on the new lenis monorepo.
