### ISSUE TITLE
Help needed with react Lenis

### ISSUE THREAD

**Issue by umarnauman0** [studio-freight/react-lenis#32]
Hello, I am trying to implement react-lenis within my react vite project. I have the smooth scrolling working but I have an anchor tag within my nav component and when I follow the default settings and add the lenis.scrollTo on my react onclick func and it returns by saying that lenis.scrollTo is not a function. I am not sure what I am doing. I tried finding tutorials on react-lenis but cant seem to find much on it, specially on scrollTo. 

PS: I couldn't add the help wanted label for some odd reason

**Comment by clementroche** [comment]
please provide a codesandbox

**Comment by umarnauman0** [comment]
Hello, created this very simple codesandbox. In the app.jsx it has the root and the issue is within my navigation, I don't know how to make a scrollTo using the react-lenis, BTW: I tried lenis and useLenis

The sandbox is very limited and is missing other parts but the main focus is within the navigation. also, the navigation import says its wrong but seems to work. Not sure why the link is that long!

https://codesandbox.io/p/sandbox/unruffled-cartwright-w3qqts?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clocwb3du0008356iqb7ib9p6%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clocwb3du0003356i4w2ddfr8%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clocwb3du0005356i6tigqokd%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clocwb3du0007356ihi1shcbk%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clocwb3du0003356i4w2ddfr8%2522%253A%257B%2522id%2522%253A%2522clocwb3du0003356i4w2ddfr8%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clocwb3du0002356iq2rnkdwc%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522id%2522%253A%2522clocwbhuu006q356i2owxd316%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clocwbhuu006q356i2owxd316%2522%257D%252C%2522clocwb3du0007356ihi1shcbk%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clocwb3du0006356ikhhrep7l%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clocwb3du0007356ihi1shcbk%2522%252C%2522activeTabId%2522%253A%2522clocwb3du0006356ikhhrep7l%2522%257D%252C%2522clocwb3du0005356i6tigqokd%2522%253A%257B%2522id%2522%253A%2522clocwb3du0005356i6tigqokd%2522%252C%2522activeTabId%2522%253A%2522clocwe01t00fu356i3rj699hs%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clocwb3du0004356iqv0pjebe%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%257D%252C%257B%2522id%2522%253A%2522clocwe01t00fu356i3rj699hs%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clocw531n002wd8fj0e3u959i%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A26.502347417840383%257D

**Comment by clementroche** [comment]
useLenis is a react hook

```js
const lenis = useLenis()
  
const handleScroll = () => {
    lenis.scrollTo("#about");
};
```
