### ISSUE TITLE
problem after update 

### ISSUE THREAD

**Issue by onopko81** [studio-freight/react-lenis#33]
Hi, after update there is error if use react lenis.

Error: (0 , react__WEBPACK_IMPORTED_MODULE_0__.createContext) is not a function

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
o
node_modules/@studio-freight/react-lenis/dist/react-lenis.modern.mjs (1:625)
(rsc)/./node_modules/@studio-freight/react-lenis/dist/react-lenis.modern.mjs

**Comment by onopko81** [comment]
my package.json

{
  "name": "start",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@react-three/fiber": "8.15.8",
    "@studio-freight/react-lenis": "0.0.36",
    "next": "14.0.0",
    "next-fonts": "1.5.1",
    "react": "^18",
    "react-dom": "^18",
    "three": "0.158.0",
    "three-stdlib": "2.28.3",
    "tunnel-rat": "0.1.2",
    "uuid": "9.0.1"
  },
  "devDependencies": {
    "autoprefixer": "^10",
    "eslint": "^8",
    "eslint-config-next": "14.0.0",
    "file-loader": "6.2.0",
    "glslify": "7.1.1",
    "glslify-loader": "2.0.0",
    "postcss": "^8",
    "raw-loader": "4.0.2",
    "tailwindcss": "^3",
    "url-loader": "4.1.1"
  }
}

**Comment by clementroche** [comment]
Are you using it in a client component ? 'use client' ?

**Comment by onopko81** [comment]
with 'use client' in layout page working in homepage. but if use in about page, useeffect there is the error: 
You're importing a component that needs useEffect. It only works in a Client Component but none of its parents are marked with "use client", so they're Server Components by default.
Learn more: https://nextjs.org/docs/getting-started/react-essentials

**Comment by clementroche** [comment]
please provide a reproduction link

**Comment by onopko81** [comment]
hi, this is link:
https://codesandbox.io/p/sandbox/zealous-mestorf-qt629s?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cloe1jegl000b3b6p4kv4zb8b%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cloe1jegk00033b6pzxjq4oo4%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cloe1jegk00083b6psbrbyxng%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cloe1jegk000a3b6pefx98rmn%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cloe1jegk00033b6pzxjq4oo4%2522%253A%257B%2522id%2522%253A%2522cloe1jegk00033b6pzxjq4oo4%2522%252C%2522activeTabId%2522%253A%2522cloe1lkd500nw3b6pkul2nakf%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cloe1jegk00023b6p4cnwz8yz%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522id%2522%253A%2522cloe1jm6i004r3b6p318szw0w%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fapp%252Flayout.tsx%2522%252C%2522id%2522%253A%2522cloe1lkd500nw3b6pkul2nakf%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fapp%252Fabout%252Fpage.js%2522%252C%2522id%2522%253A%2522cloe75x8z00483b6p92fe8gd9%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%257D%252C%2522cloe1jegk000a3b6pefx98rmn%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cloe1jegk00093b6ppw5q6hnb%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252Fabout%2522%257D%255D%252C%2522id%2522%253A%2522cloe1jegk000a3b6pefx98rmn%2522%252C%2522activeTabId%2522%253A%2522cloe1jegk00093b6ppw5q6hnb%2522%257D%252C%2522cloe1jegk00083b6psbrbyxng%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cloe1jegk00043b6puhl1gi0c%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522id%2522%253A%2522cloe1jegk00053b6puwnhmp8c%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522build%2522%257D%252C%257B%2522id%2522%253A%2522cloe1jegk00063b6pimksm86i%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%257D%252C%257B%2522id%2522%253A%2522cloe1jegk00073b6ptgtyfy2l%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522install%2522%257D%255D%252C%2522id%2522%253A%2522cloe1jegk00083b6psbrbyxng%2522%252C%2522activeTabId%2522%253A%2522cloe1jegk00073b6ptgtyfy2l%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

**Comment by onopko81** [comment]
you can share a boilerplate with nextjs 14 with multi page and ssr?

**Comment by clementroche** [comment]
it works if you add 'use client' on top for your page, i see nothing related with your initial issue, react-lenis is working as expected.

```js
'use client';

import { useEffect } from "react";

export default function About() {
  useEffect(() => {
    console.log("start");
  }, []);

  return (
    <>
      <h1>About</h1>
    </>
  );
}
```
