### ISSUE TITLE
Using `<ReactLenis root/>` for specific page only Next.js

### ISSUE THREAD

**Issue by nhtoby311** [studio-freight/react-lenis#34]
I want to have Lenis only on certain page route, so I try to have the component only at the page itself, for example:

```tsx
//pages/about.tsx
...
return (
  <ReactLenis root>
    {//About page DOM}
  </ReactLenis>
)

```

As user navigate to `/about` page, the Lenis component will be mounted only then. Would this approach good enough?

**Comment by clementroche** [comment]
it should work, that's how we use it on our starter, react-lenis is taking care of everything.

https://github.com/studio-freight/satus

**Comment by nhtoby311** [comment]
Thanks! It works well, just I wonder if there is any caveats by simply doing this!
