### ISSUE TITLE
Re-calculate Lenis scroll

### ISSUE THREAD

**Issue by nhtoby311** [studio-freight/react-lenis#36]
In my case, I have few images assets in the page took time to load, combine with Framer Motion delay animate. This causes in some cases, the scrollable range calculated from Lenis is less than the page actually is after all images is loaded.

 Is there a way I can re-update the initial Lenis scroll distance calculation? 
 
![asd](https://github.com/studio-freight/react-lenis/assets/52330522/c4469d89-183c-4e6f-9e14-f4850ed666f2)

**Comment by clementroche** [comment]
please provide a reproduction link

**Comment by nhtoby311** [comment]
I tried to reproduce it [here](https://codesandbox.io/p/devbox/lenis-init-scroll-issue-cf767n?file=%2Fpages%2Fissue%2F%5Bslug%5D.tsx%3A15%2C31) on codesandbox, but don't know what is preventing me to replicate the issue there, as I have the same dependencies version and layout structure. Because of that, I'm interested in some way to solve it on my actual code like way to manually re-calculate the scroll dimension, so is it possible?

Below is the `scrollHeight` value I receive in my code, where on initial visit the page, no img cached, the dimensions returns 1409, which is lower than the whole page load should be, and the other one is the cached img, where the dimensions works properly.

Disable cache:
![image](https://github.com/studio-freight/react-lenis/assets/52330522/dc6a4f27-3f66-4f5f-94dd-f587c04f7ec4)

Img cached:
![image](https://github.com/studio-freight/react-lenis/assets/52330522/a56da9fe-b910-45cc-8bd7-d6612c3f3e5e)

**Comment by clementroche** [comment]
Lenis automatically recalculates its own dimensions based on `ResizeObserver`, even if your images are lazy loaded, it should be exact. I can't help you if you can't reproduce it outside of your application.

You can still call `.resize()`, it will recalculate dimensions manually.

**Comment by nhtoby311** [comment]
Great thanks! That would be my workaround for now for my code, as I can't really figure what the issue could be.
