### ISSUE TITLE
Lenis not scrolling immediately when scrolled

### ISSUE THREAD

**Issue by MM3693** [studio-freight/react-lenis#37]
I am using Next 14 with the app router. When I scroll the page, the lenis scrolls after sometime (1-2 seconds) which is causing this weird scroll behaviour. 

React lenis version: `0.0.40`

Here is the SmoothScrolling.tsx file
```javascript
'use client'
import { ReactLenis, useLenis } from '@studio-freight/react-lenis'

function SmoothScrolling({ children }: { children: React.ReactNode }) {
  const lenis = useLenis(({ scroll }) => {
    console.log({ scroll })
  })

  return <ReactLenis root>{children}</ReactLenis>
}

export default SmoothScrolling
```

Here is the layout.tsx file
```javascript
<SmoothScrolling>
    <Navbar />
    <main className="w-screen h-full min-h-[90vh] shadow-main-layout-bottom flex justify-center items-center bg-white">
         {children}
     </main>
     <Footer />
</SmoothScrolling>
```

This is scroll behavior when scrolled. In the console, I am getting realtime value of the scroll but the scroll behaviour is not reflected instantly

https://github.com/studio-freight/react-lenis/assets/132553635/824e6317-7fba-40cb-bef6-a01beaeee966

**Comment by clementroche** [comment]
Please provide a reproduction link

**Comment by MM3693** [comment]
Hi @clementroche 
You can experience the scrolling issue on this link.
https://site098.vercel.app/

**Comment by riju-stone** [comment]
I am facing a similar issue on both lenis and react-lenis. There is severe lag when scrolling through the pages.

**Comment by clementroche** [comment]
HTML element should be `scroll-behavior: auto`

Please read the [documentation](https://github.com/studio-freight/lenis?tab=readme-ov-file#recommended-css)

**Comment by MM3693** [comment]
That worked. Smooth scroll now. 
Thanks @clementroche
