### ISSUE TITLE
Unexpected console log in production

### ISSUE THREAD

**Issue by kilimanjjjaro** [studio-freight/react-lenis#5]
Thank you very much for the library, you did a great job guys. Today I implemented it in my Next App and it works without problems. I only found a slightly annoying console.log, specifically it is in the react-lenis.modern.mjs file.

`console.log("Lenis",r)`

I really don't know if this is intentional but maybe they should remove it so that it doesn't appear in production since it is unnecessary and could even be considered a bad practice. Anyway, I removed it from my local but if one day the library is updated, it will appear again.

Again, thank you very much for your work. Have a great weekend.

**Comment by arzafran** [comment]
@kilimanjjjaro thanks for the heads up, we added it for testing purposes and forgot to remove it, we got used to Next.js console log removal in prod, and maybe should put something in place here so the built files are free from logs.

have a great weekend you too!

**Comment by kilimanjjjaro** [comment]
Thank you, I just made a pull request, I didn't expect such a quick response haha.
