### ISSUE TITLE
Q: How to use scroll snap in react lenis?

### ISSUE THREAD

**Issue by sushanyadav** [studio-freight/react-lenis#7]
**Sorry, not an issue but a question.**

Is there any way I can use scroll snap with react lenis ? I saw a plugin called [lenis-scroll-snap](https://github.com/funkhaus/lenis-scroll-snap) but I am unsure how we can use it on react.

**Comment by clementroche** [comment]
Sorry but we're not responsible for this plugin so you shouldn' leave this issue here.

just use `lenis = useLenis()`
then `new ScrollSnap(lenis, config)`

**Comment by sushanyadav** [comment]
apologies @clementroche . Thank you so much
